### ISSUE TITLE
Enable key replication across regions when 'multi_region' option is selected

### ISSUE THREAD

**Issue by nsvijay04b1** [cloudposse/terraform-aws-kms-key#32]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Expected Behavior

Enable key replication across regions when 'multi_region' option is selected

## Use Case

KMS supports key replication. It is logical to support it from this module as it already support creation of multi-region key.

## Describe Ideal Solution

This module should use below Terraform recourse   and create replication             https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kms_replica_key

## Alternatives Considered

If i have to use 'multi-region' now i have to implement on top myself using                 https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kms_replica_key

**Comment by Nuru** [comment]
Closing as `wontfix` because replica keys need to be created in the region in which they will be used. This means you need an AWS provider for that region. Because [providers cannot be parameterized](https://github.com/hashicorp/terraform/issues/19932), it is impractical to create all the replica keys in a single module. You need to create the replica keys outside of this module, configuring the providers as needed.
